name: publish-app

# Controls when the workflow will run
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - id: run-action
        uses: deta/publish-pc-app@v0-v1
        with:
          app: "f4c522aa-617e-4343-a958-0cdeed4f40a2"
          desc: "share stuff across your personal devices"
        env:
          DETA_ACCESS_TOKEN: ${{ secrets.DETA_ACCESS_TOKEN }}
